// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['jQuery', 'Underscore', 'Backbone'], function($, _, Backbone) {
    return {
      View: Backbone.View.extend({
        initialize: function(options) {
          var mixins,
            _this = this;
          Backbone.View.prototype.initialize.apply(this, arguments);
          this.teardowns = [];
          if (mixins = options != null ? options.mixins : void 0) {
            _.each(mixins, function(mi) {
              var key, value;
              for (key in mi) {
                if (!__hasProp.call(mi, key)) continue;
                value = mi[key];
                if (key !== 'setup' && key !== 'teardown') {
                  _this[key] = value;
                }
              }
              if (mi.setup) {
                mi.setup.apply(_this);
              }
              if (mi.teardown) {
                _this.teardowns.push(mi.teardown);
              }
            });
          }
        },
        remove: function() {
          var _this = this;
          _.each(this.teardowns, function(td) {
            td.apply(_this);
          });
          Backbone.View.prototype.remove.apply(this, arguments);
        }
      })
    };
  });

}).call(this);
