// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty;

  define(['jQuery', 'Underscore', 'Backbone', 'plugins/Subscribable'], function($, _, Backbone, Subscribable) {
    return {
      View: Backbone.View.extend({
        initialize: function(options) {
          var mixins,
            _this = this;
          Backbone.View.prototype.initialize.apply(this, arguments);
          this.teardowns = [];
          mixins = [Subscribable];
          if (options != null ? options.mixins : void 0) {
            mixins = mixins.concat(options.mixins);
          }
          _.each(mixins, function(mi) {
            var key, su, td, value;
            su = mi.setup;
            td = mi.teardown;
            for (key in mi) {
              if (!__hasProp.call(mi, key)) continue;
              value = mi[key];
              if (key !== 'setup' && key !== 'teardown') {
                _this[key] = value;
              }
            }
            if (su) {
              su.apply(_this);
            }
            if (td) {
              _this.teardowns.push(td);
            }
          });
        },
        remove: function() {
          var _this = this;
          _.each(this.teardowns, function(td) {
            td.apply(_this);
          });
          Backbone.View.prototype.remove.apply(this, arguments);
        }
      })
    };
  });

}).call(this);
