// Generated by CoffeeScript 1.4.0
(function() {

  define(['jQueryUI', 'Underscore', 'Backpack', 'TaskCollection', 'ListView', 'plugins/Sortable', 'TaskView', 'EditTaskView', 'text!template/MainView.html'], function($, _, Backpack, TaskCollection, ListView, Sortable, TaskView, EditTaskView, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        "click #newTaskBtn": "onNewButtonClicked",
        "click #showAllLink": "onShowAllLinkClicked"
      },
      initialize: function(options) {
        var taskList,
          _this = this;
        Backpack.View.prototype.initialize.apply(this, arguments);
        this.render();
        $('#datePicker').datepicker({
          onSelect: function(dateText, inst) {
            Backbone.trigger("UPDATE_LIST", {
              dateText: dateText,
              date: $('#datePicker').datepicker("getDate")
            });
          },
          onClose: function(dateText, inst) {
            if (!dateText || dateText.length === 0) {
              Backbone.trigger("UPDATE_LIST");
            }
          }
        });
        taskList = new TaskCollection();
        new EditTaskView({
          el: "#dialogContainer",
          collection: taskList,
          subscribers: {
            SHOW_TASK_EDITOR: 'show'
          }
        });
        new ListView({
          el: "#taskListView",
          itemClass: TaskView,
          collection: taskList,
          plugins: [Sortable],
          subscribers: {
            UPDATE_LIST: 'filterChildren'
          }
        });
        taskList.load();
        Backbone.trigger("UPDATE_LIST");
      },
      render: function(model, value, options) {
        this.$el.html(this.template());
        return this;
      },
      onNewButtonClicked: function() {
        Backbone.trigger("SHOW_TASK_EDITOR");
      },
      onShowAllLinkClicked: function() {
        Backbone.trigger("UPDATE_LIST");
      },
      onUpdateList: function(options) {
        var hasFilter, title;
        hasFilter = false;
        if (options) {
          if (options.tag) {
            title = _.template("Tasks with tag '<%= tag %>'", options);
            hasFilter = true;
          } else if (options.dateText) {
            title = _.template("Tasks created at '<%= dateText %>'", options);
            hasFilter = true;
          }
        }
        if (hasFilter) {
          $('#showAllLink').css("display", "block");
        } else {
          $('#showAllLink').css("display", "none");
          $('#datePicker').val("");
          title = "All Tasks";
        }
        $("#taskListTitle").text(title);
      }
    });
  });

}).call(this);
