// Generated by CoffeeScript 1.4.0
(function() {

  define(['jQuery', 'Underscore', 'Backbone', 'text!template/TaskView.html'], function($, _, Backbone, viewTemplate) {
    return Backbone.View.extend({
      template: _.template(viewTemplate),
      events: {
        "click .editBtn": "onEditButtonClicked",
        "click .deleteBtn": "onDeleteButtonClicked"
      },
      initialize: function() {
        this.listenTo(this.model, "change", this.render);
        this.listenTo(this.model, "destroy", this.remove);
      },
      render: function(model, value, options) {
        var attrs, d, tagContainer,
          _this = this;
        attrs = this.model.attributes;
        d = new Date(attrs["createdAt"]);
        attrs["formattedTime"] = _.template("<%=month%>/<%=day%>/<%=year%> <%=hours%>:<%=minutes%>", {
          year: d.getFullYear(),
          month: d.getMonth() + 1,
          day: d.getDate(),
          hours: d.getHours(),
          minutes: d.getMinutes()
        });
        this.$el.html(this.template(attrs));
        tagContainer = this.$el.find(".tagContainer");
        _.each(attrs["tags"], function(tag, idx) {
          var anchor;
          if (idx > 0) {
            tagContainer.append("&nbsp;");
          }
          anchor = $(document.createElement("a")).prop({
            href: "javascript:void(0)"
          }).text(tag).click(function(evt) {
            Backbone.trigger("UPDATE_LIST", {
              tag: tag
            });
          });
          tagContainer.append(anchor);
        });
        return this;
      },
      onEditButtonClicked: function() {
        Backbone.trigger("SHOW_TASK_EDITOR", this.model);
      },
      onDeleteButtonClicked: function() {
        if (confirm(_.template("Are you sure you want to delete '<%=text%>'?", this.model.attributes))) {
          this.model.destroy();
        }
      },
      remove: function() {
        this.stopListening(this.model);
        Backbone.View.prototype.remove.call(this);
      }
    });
  });

}).call(this);
