// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jQuery', 'Underscore', 'Backbone', 'TaskView', 'text!template/TaskView.html'], function($, _, Backbone, TaskView, taskViewTemplate) {
    return TaskView = (function(_super) {

      __extends(TaskView, _super);

      function TaskView() {
        return TaskView.__super__.constructor.apply(this, arguments);
      }

      TaskView.prototype.template = _.template(taskViewTemplate);

      TaskView.prototype.events = {
        "click .editBtn": "onEditButtonClicked",
        "click .deleteBtn": "onDeleteButtonClicked"
      };

      TaskView.prototype.initialize = function() {
        this.listenTo(this.model, "change", this.render);
        return this.listenTo(this.model, "destroy", this.remove);
      };

      TaskView.prototype.render = function(model, value, options) {
        var attrs, d, tagContainer;
        attrs = this.model.attributes;
        d = new Date(attrs["createdAt"]);
        attrs["formattedTime"] = _.template("<%=month%>/<%=day%>/<%=year%> <%=hours%>:<%=minutes%>", {
          year: d.getFullYear(),
          month: d.getMonth() + 1,
          day: d.getDate(),
          hours: d.getHours(),
          minutes: d.getMinutes()
        });
        $(this.el).html(this.template(attrs));
        tagContainer = $(this.el).find(".tagContainer");
        _.each(attrs["tags"], function(tag, idx) {
          var anchor;
          if (idx > 0) {
            tagContainer.append("&nbsp;");
          }
          anchor = $(document.createElement("a")).prop({
            href: "javascript:void(0)"
          }).text(tag).click(function(evt) {
            return pubsub.trigger("UPDATE_TASK_LIST", {
              tag: tag
            });
          });
          return tagContainer.append(anchor);
        });
        return this;
      };

      TaskView.prototype.onEditButtonClicked = function() {
        return pubsub.trigger("SHOW_TASK_EDITOR", this.model);
      };

      TaskView.prototype.onDeleteButtonClicked = function() {
        if (confirm(_.template("Are you sure you want to delete '<%=text%>'?", this.model.attributes))) {
          return this.model.destroy();
        }
      };

      TaskView.prototype.destroy = function() {
        this.stopListening(this.model);
        return Backbone.View.prototype.remove.call(this);
      };

      return TaskView;

    })(Backbone.View);
  });

}).call(this);
