// Generated by CoffeeScript 1.4.0
(function() {

  define(['jQuery', 'Underscore', 'Backbone', 'TaskView'], function($, _, Backbone, TaskView) {
    return Backbone.View.extend({
      el: "#taskListView",
      initialize: function() {
        this.collection.on("add remove reset", this.render, this);
        pubsub.on("UPDATE_TASK_LIST", this.render, this);
        this._taskViews = [];
      },
      render: function(options) {
        var models;
        models = this.collection.filter(options);
        this.clearTaskViews();
        if (models.length > 0) {
          _.each(models, this.addTaskView, this);
        } else {
          $(this.el).html("No Tasks");
        }
        return this;
      },
      addTaskView: function(task) {
        var view;
        view = new TaskView({
          model: task
        });
        $(this.el).append(view.render().$el);
        this._taskViews.push(view);
      },
      clearTaskViews: function() {
        var i, _i, _ref;
        for (i = _i = _ref = this._taskViews.length - 1; _i >= 0; i = _i += -1) {
          this.removeTaskView(i);
        }
      },
      removeTaskView: function(index) {
        this._taskViews[index].destroy();
        this._taskViews.splice(index, 1);
      },
      destroy: function() {
        this.collection.off("add remove reset", this.render);
        pubsub.off("UPDATE_TASK_LIST", this.render, this);
        Backbone.View.prototype.remove.call(this);
      }
    });
  });

}).call(this);
