// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['Underscore', 'Backbone', 'TaskModel'], function(_, Backbone, TaskModel) {
    return TaskModel = (function(_super) {

      __extends(TaskModel, _super);

      function TaskModel() {
        return TaskModel.__super__.constructor.apply(this, arguments);
      }

      TaskModel.prototype.isCreatedAt = function(date) {
        var d;
        d = new Date(this.get("createdAt"));
        return d.getFullYear() === date.getFullYear() && d.getMonth() === date.getMonth() && d.getDate() === date.getDate();
      };

      TaskModel.prototype.hasTag = function(tag) {
        var ret, tags;
        tags = this.get("tags");
        return ret = tags ? tags.indexOf(tag) >= 0 : false;
      };

      return TaskModel;

    })(Backbone.Model);
  });

}).call(this);
