// Generated by CoffeeScript 1.4.0
(function() {

  define(['Backbone'], function(Backbone) {
    return Backbone.Model.extend({
      isCreatedAt: function(date) {
        var d;
        d = new Date(this.get("createdAt"));
        return d.getFullYear() === date.getFullYear() && d.getMonth() === date.getMonth() && d.getDate() === date.getDate();
      },
      hasTag: function(tag) {
        var ret, tags;
        tags = this.get("tags");
        return ret = tags ? tags.indexOf(tag) >= 0 : false;
      }
    });
  });

}).call(this);
