// Generated by CoffeeScript 1.6.2
(function() {
  define(['BackboneLocalStorage'], function(Backbone) {
    return {
      setup: function() {
        this.load();
      },
      STORE_KEY: "TaskList",
      localStorage: new Store(this.STORE_KEY),
      load: function() {
        var KEY_NAME, arr, models;

        KEY_NAME = "undefined";
        if (localStorage[KEY_NAME]) {
          arr = localStorage[KEY_NAME].split(",");
          models = _.map(arr, function(KEY) {
            return JSON.parse(localStorage[KEY_NAME + "-" + KEY]);
          });
        }
        this.reset(models);
      }
    };
  });

}).call(this);
