// Generated by CoffeeScript 1.6.2
(function() {
  define(['jQueryUITouchPunch', 'Backpack', 'LocalStorage', 'TaskModel', 'TaskView', 'EditTaskView', 'text!template/MainView.html'], function($, Backpack, LocalStorage, TaskModel, TaskView, EditTaskView, viewTemplate) {
    return Backpack.View.extend({
      template: _.template(viewTemplate),
      events: {
        'click #newTaskBtn': 'onNewButtonClicked',
        'click #showAllLink': 'onShowAllLinkClicked'
      },
      initialize: function(options) {
        var taskList;

        Backpack.View.prototype.initialize.apply(this, arguments);
        this.render();
        $('#datePicker').datepicker({
          onSelect: function(dateText, inst) {
            Backbone.trigger('UPDATE_LIST', {
              dateText: dateText,
              date: $('#datePicker').datepicker('getDate')
            });
          },
          onClose: function(dateText, inst) {
            if (!dateText || dateText.length === 0) {
              Backbone.trigger('UPDATE_LIST');
            }
          }
        });
        taskList = new Backpack.Collection(null, {
          model: TaskModel,
          plugins: [LocalStorage]
        });
        new EditTaskView({
          el: '#dialogContainer',
          collection: taskList,
          subscribers: {
            SHOW_TASK_EDITOR: 'show'
          }
        });
        new Backpack.ListView({
          el: '#taskListView',
          itemClass: TaskView,
          collection: taskList,
          plugins: [Backpack.ContainerPlugin, Backpack.SortablePlugin],
          subscribers: {
            UPDATE_LIST: 'filterChildren'
          }
        });
        Backbone.trigger('UPDATE_LIST');
      },
      render: function(model, value, options) {
        this.$el.html(this.template());
        return this;
      },
      onNewButtonClicked: function() {
        Backbone.trigger('SHOW_TASK_EDITOR');
      },
      onShowAllLinkClicked: function() {
        Backbone.trigger('UPDATE_LIST');
      },
      onUpdateList: function(options) {
        var hasFilter, title;

        hasFilter = false;
        if (options) {
          if (options.tag) {
            title = _.template('Tasks with tag "<%= tag %>"', options);
            hasFilter = true;
          } else if (options.dateText) {
            title = _.template('Tasks created at "<%= dateText %>"', options);
            hasFilter = true;
          }
        }
        if (hasFilter) {
          $('#showAllLink').css('display', 'block');
        } else {
          $('#showAllLink').css('display', 'none');
          $('#datePicker').val('');
          title = 'All Tasks';
        }
        $('#taskListTitle').text(title);
      }
    });
  });

}).call(this);
